export * from './endpointsRecommendedBodyParameterPostfix.rule';
export * from './endpointsRecommendedQueryPostfix.rule';
export * from './endpointsRecommendedResponsePostfix.rule';
export * from './recommendedBodyModelName.rule';
export * from './recommendedFilterPostfix.rule';
export * from './recommendedModelBodyFieldPostfix.rule';
export * from './recommendedPostfixForCreateModels.rule';
export * from './recommendedPostfixForUpdateModels.rule';
export * from './endpointsUpdateRequestResponseMatch.rule';
