name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Generate coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
