- name: Checkout code
  uses: actions/checkout@master
- name: Update diagram
  uses: githubocto/repo-visualizer@main
  with:
    output_file: 'assets/diagram.svg'
    excluded_paths: 'dist,node_modules,.github,.husky,assets,coverage,docs,examples,temp'